version: '3'

services:
  client:
    build: ./client
    command: nodemon -L --exec yarn start
    ports: 
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules

  database:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      # - ./database/data:/var/lib/postgresql/data

  retriever:
    build: ./retriever
    command: python3 app.py
    ports:
      - "4000:4000"
    volumes:
      - ./retriever:/app
    depends_on:
      - database