version: '3'

services:
  client:
    build: ./client
    command: nodemon -L --exec yarn start
    ports: 
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules

  database:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      # - ./database/data:/var/lib/postgresql/data

  cache:
    image: redis:5.0.5-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./cache/redis.conf:/usr/local/etc/redis/redis.conf

  retriever:
    build: ./retriever
    command: python3 app.py
    ports:
      - "4000:4000"
    volumes:
      - ./retriever:/app
    depends_on:
      - database
      - cache

  mbls:
    build: ./mbls
    command: python3 app.py
    ports:
      - "5000:5000"
    volumes:
      - ./mbls:/app
    depends_on:
      - database
      - cache